var a = document.getElementsByTagName("value");
document.getElementById("result").innerHTML = a;
const d = new Date();
thisDate = d.getDate();
thisMonth = d.getMonth();
thisYear = d.getFullYear();
document.getElementById("demo1").innerHTML = thisDate + ".";
document.getElementById("demo2").innerHTML = thisMonth + 1 + ".";
document.getElementById("demo3").innerHTML = thisYear;